In [1]:
import numpy
arr = numpy.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
import numpy as np
arr1 = np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [4]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
#3 dimension having two 2 dimensional arrays
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#finding the number of dimensions
print("No. of dimension: ",arr3.ndim) 

#finding the shape of an array
print("Shape of the array: ",arr3.shape)

#finding the size(total number of elements) of an array
print("Size of the array: ",arr3.size)

No. of dimension:  3
Shape of the array:  (2, 2, 3)
Size of the array:  12


In [8]:
# Creating array from the list having float data type
a = np.array([[1,2,3],[4,5,6]], dtype='float')
print("Array created using passed list:\n",a)

Array created using passed list:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
#Creating array from tuple
b = np.array((1,2,3))
print("\nArray created using passed tuple:\n",b)


Array created using passed tuple:
 [1 2 3]


In [10]:
#Creating an array 3X4 with all zeroes
c = np.zeros((3,4))
print("\nAn array initialized with all zeros:\n",c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
#Creating a constant value array of complex type
d = np.full((3,4), 6, dtype="complex")
print("\nAn array initialized with all 6s. Array type is complex:\n",d)



An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]]


In [16]:
# Creating an array with random values
e = np.random.random((2,2))
print("\nA random array:\n",e)


A random array:
 [[0.82425192 0.79870311]
 [0.40533161 0.58838087]]


In [19]:
#create an array from 0 to 30 with step 5
f = np.arange(0,31,5)
print("\nA sequence of array with step 5 from 0 to 31:\n",f)


A sequence of array with step 5 from 0 to 31:
 [ 0  5 10 15 20 25 30]


In [23]:
#Create a sequence of 11 values in the range 0 to 5
g = np.linspace(10.5,15,10)
print(g) 

[10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15. ]


In [25]:
h = np.linspace(10,20,11)
print(h)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [37]:
#Reshaping array
arr4 = np.array([[1,2,3,4],
                 [4,5,6,7],
                 [3,4,6,9]])

newarr4 = arr4.reshape(2,2,3)
print("\nOriginal Array:\n",arr4)
print("\nNew array:\n",newarr4)
print("\n")
print(newarr4.shape)
print(newarr4.ndim)


Original Array:
 [[1 2 3 4]
 [4 5 6 7]
 [3 4 6 9]]

New array:
 [[[1 2 3]
  [4 4 5]]

 [[6 7 3]
  [4 6 9]]]


(2, 2, 3)
3


In [40]:
#Flatten array
arr5 = np.array([[1,2,3],[4,5,6]])
flarr = arr5.flatten()
print("\nOriginal Array:\n",arr5)
print("\nNew Array:\n",flarr)
print(flarr.ndim)


Original Array:
 [[1 2 3]
 [4 5 6]]

New Array:
 [1 2 3 4 5 6]
1


In [47]:
#creating an array of the give shape and populate it
#with random samples from a uniform distribution over(0,1)
arr6 = np.random.rand(2,3)
print(arr6)
print("\n")
arr7 = np.random.rand(5)
print(arr7)

[[0.99204711 0.81561018 0.70968117]
 [0.69027109 0.83723765 0.86197212]]


[0.36900615 0.43739166 0.42923835 0.23600744 0.0766677 ]


In [53]:
#Generating 5 random integer numbers between 15 and 30
r = np.random.randint(15,30,5)
print("5 random integers between 15 and 30:\n",r)

5 random integers between 15 and 30:
 [20 16 23 19 27]


In [63]:
#np.matrix returns a matrix from ana array like object
m = np.matrix(np.arange(12).reshape((3,4)))
print(m)

n = np.matrix([[5,6,7],[2,3,8]])
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[5 6 7]
 [2 3 8]]


In [66]:
#Python program to demonstrate binary operators using Numpy

i = np.array([[1,2],
             [3,4]])
j = np.array([[4,3],
             [2,1]])
print(i)
print(j)

#adding arrays
print("The sum of two arrays:\n", i+j)

#multiplying arrays(elementwise multiplication)
print("Array multiplication:\n", i*j)

#matrix multiplication
print("Matrix multiplication:\n",i.dot(j))


[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
The sum of two arrays:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [65]:
#PANDAS

In [72]:
import pandas as pd
import numpy as np

#series
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[0,1,2,3])
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [74]:
#DataFrame
data1 = [1,2,3,4,5]
df1 = pd.DataFrame(data1)
print(df1)

   0
0  1
1  2
2  3
3  4
4  5


In [75]:
data2 = [['Alex',10],['Bob',12],['Clarke',13]]
df2 = pd.DataFrame(data2)
print(df2)

        0   1
0    Alex  10
1     Bob  12
2  Clarke  13


In [76]:
#Creating DataFrame using dictionary
data3 = {'Name':['Tom','Jack','Steve','Ricky'],'Age':[28,32,45,31]}
df3 = pd.DataFrame(data3)
print(df3)

    Name  Age
0    Tom   28
1   Jack   32
2  Steve   45
3  Ricky   31


In [77]:
data4 = [{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df4 = pd.DataFrame(data4)
print(df4)

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [81]:
#Data Analysis Using Pandas

#Reading SCV File with Pandas

In [83]:
import pandas as pd
df5 = pd.read_csv("emp.csv")
print(df5)

     Name   Hire Date  Salary  leaves
0  Graham  13/02/2022   50000       1
1   Harry  20/01/2021  100000       5
2    Anna  22/05/2021  150000       8
3    Niel  18/11/2021  120000       5


In [91]:
# Reading the data from a specific column
print(df5['Salary'])

0     50000
1    100000
2    150000
3    120000
Name: Salary, dtype: int64


In [92]:
print(df5[['Salary']]) #With column name

   Salary
0   50000
1  100000
2  150000
3  120000


In [94]:
sum(df5['Salary']) #Sum of the values from a column

420000

In [86]:
sum(df5['leaves'])

19

In [96]:
print(df5[['Name','Salary']]) #Getting only two columns

     Name  Salary
0  Graham   50000
1   Harry  100000
2    Anna  150000
3    Niel  120000


In [103]:
#Getting a random row
print(df5.sample(n=1))
print(df5.shape)

     Name   Hire Date  Salary  leaves
0  Graham  13/02/2022   50000       1
(4, 4)


In [ ]:
#Adding new column in dataframe


In [113]:
work_hours = [8,6,7,8]

df5['work_hours'] = work_hours

In [107]:
df5

Name   Hire Date  Salary  leaves  work_hours
0  Graham  13/02/2022   50000       1           8
1   Harry  20/01/2021  100000       5           6
2    Anna  22/05/2021  150000       8           7
3    Niel  18/11/2021  120000       5           8

In [114]:
address = ['Baneshwor','Thapathali','Lalitpur','Baluwatar']
df5['Address'] = address

In [115]:
df5

Name   Hire Date  Salary  leaves  work_hours     Address
0  Graham  13/02/2022   50000       1           8   Baneshwor
1   Harry  20/01/2021  100000       5           6  Thapathali
2    Anna  22/05/2021  150000       8           7    Lalitpur
3    Niel  18/11/2021  120000       5           8   Baluwatar

In [116]:
# DELETING the particular column from DATAFRAME


In [117]:
del df5['leaves']

In [118]:
df5

Name   Hire Date  Salary  work_hours     Address
0  Graham  13/02/2022   50000           8   Baneshwor
1   Harry  20/01/2021  100000           6  Thapathali
2    Anna  22/05/2021  150000           7    Lalitpur
3    Niel  18/11/2021  120000           8   Baluwatar

In [121]:
df6 = pd.read_csv('cricket.csv')
print(df6)

    Delivery  Score_ind  Score_pk
0        0.1          0         0
1        0.2          1         0
2        0.3          1         4
3        0.4          4         4
4        0.5          0         1
5        0.6          1         2
6        1.1          0         4
7        1.2          0         6
8        1.3          0         2
9        1.4          2         4
10       1.5          1         6
11       1.6          0         1
12       2.1          0         0
13       2.2          1         0
14       2.3          2         4
15       2.4          0         6
16       2.5          1         6
17       2.6          4         0
18       3.1          4         0
19       3.2          1         0
20       3.3          1         1
21       3.4          0         1
22       3.5          0         1
23       3.6          0         1


In [122]:
#Viewing only first 5 rows
df6.head()

Delivery  Score_ind  Score_pk
0       0.1          0         0
1       0.2          1         0
2       0.3          1         4
3       0.4          4         4
4       0.5          0         1

In [127]:
#viewing last 5 rows
df6.tail()

Delivery  Score_ind  Score_pk
19       3.2          1         0
20       3.3          1         1
21       3.4          0         1
22       3.5          0         1
23       3.6          0         1

In [128]:
#viewing first 10 rows
df6.head(10)

Delivery  Score_ind  Score_pk
0       0.1          0         0
1       0.2          1         0
2       0.3          1         4
3       0.4          4         4
4       0.5          0         1
5       0.6          1         2
6       1.1          0         4
7       1.2          0         6
8       1.3          0         2
9       1.4          2         4

In [129]:
df6.tail(10) #last 10 rows

Delivery  Score_ind  Score_pk
14       2.3          2         4
15       2.4          0         6
16       2.5          1         6
17       2.6          4         0
18       3.1          4         0
19       3.2          1         0
20       3.3          1         1
21       3.4          0         1
22       3.5          0         1
23       3.6          0         1

In [132]:
#viewing first 5 rows from a particular column
df6['Delivery'].head() 

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
Name: Delivery, dtype: float64

In [134]:
df6['Score_ind'].head(7)

0    0
1    1
2    1
3    4
4    0
5    1
6    0
Name: Score_ind, dtype: int64

### Sorting the DataFrame based on a column

In [135]:
df6.sort_values('Score_ind')

Delivery  Score_ind  Score_pk
0        0.1          0         0
21       3.4          0         1
15       2.4          0         6
12       2.1          0         0
22       3.5          0         1
8        1.3          0         2
7        1.2          0         6
11       1.6          0         1
4        0.5          0         1
6        1.1          0         4
23       3.6          0         1
5        0.6          1         2
10       1.5          1         6
13       2.2          1         0
2        0.3          1         4
16       2.5          1         6
19       3.2          1         0
20       3.3          1         1
1        0.2          1         0
9        1.4          2         4
14       2.3          2         4
3        0.4          4         4
17       2.6          4         0
18       3.1          4         0

In [137]:
#sorting in descending order
df6.sort_values('Score_pk', ascending = False)

Delivery  Score_ind  Score_pk
16       2.5          1         6
7        1.2          0         6
15       2.4          0         6
10       1.5          1         6
9        1.4          2         4
2        0.3          1         4
3        0.4          4         4
6        1.1          0         4
14       2.3          2         4
5        0.6          1         2
8        1.3          0         2
21       3.4          0         1
23       3.6          0         1
22       3.5          0         1
11       1.6          0         1
4        0.5          0         1
20       3.3          1         1
19       3.2          1         0
0        0.1          0         0
18       3.1          4         0
17       2.6          4         0
13       2.2          1         0
1        0.2          1         0
12       2.1          0         0

In [138]:
#Counting the number of unique values that occur in dataset or in a column
df6.nunique()

Delivery     24
Score_ind     4
Score_pk      5
dtype: int64

In [139]:
sum(df6['Score_ind']) #total sum of a particular column

24

In [140]:
sum(df6['Score_pk'])

54